version: 2
jobs:
  build:
    working_directory: ~/Witiko/markdown
    # Distribute the testing to four nodes
    parallelism: 4
    shell: /bin/bash --login
    docker:
    - image: circleci/build-image:ubuntu-14.04-XXL-upstart-1189-5614f37
      command: /sbin/init
    steps:
    - restore_cache:
        keys:
        - markdown-v2.7.0-tl2019_pretest-{{ .Branch }}
        - markdown-v2.7.0-tl2019_pretest-master
        - markdown-v2.7.0-tl2019_pretest-
    # Install TeX Live
    - run: |
        set -e
        if [[ ! -e ~/texlive-cache ]]; then
          rsync -a --progress --exclude="mactex*" ftp.cstug.cz::pub/tex/local/tlpretest /tmp
          cd /tmp/tlpretest
          sudo ./install-tl <<<I
          sudo mv /usr/local/texlive ~/texlive-cache
          cd -
        fi
    # Install additional packages
    - run: |
        set -e
        mkdir -p ~/apt-cache/partial
        sudo apt-get -o dir::cache::archives="$HOME"/apt-cache update
        sudo apt-get -o dir::cache::archives="$HOME"/apt-cache install pandoc parallel
        sudo pip install pygments
    - save_cache:
        key: markdown-v2.7.0-tl2019_pretest-{{ .Branch }}
        paths:
        - ~/apt-cache/partial
        - ~/texlive-cache
    # Add TeX Live to the PATH environmental variable
    - run: |
        set -e
        sudo mv ~/texlive-cache /usr/local/texlive
        echo 'export PATH=/usr/local/texlive/2019/bin/x86_64-linux:"$PATH"' >>$BASH_ENV
    - checkout
    # Install the Markdown package
    - run: |
        set -e
        xetex markdown.ins
        mkdir -p                ~/texmf/{tex/{luatex,generic,latex,context/third},scripts}/markdown
        cp -f markdown.lua      ~/texmf/tex/luatex/markdown/
        cp -f markdown-cli.lua  ~/texmf/scripts/markdown/
        cp -f markdown.tex      ~/texmf/tex/generic/markdown/
        cp -f markdown.sty      ~/texmf/tex/latex/markdown/
        cp -f t-markdown.tex    ~/texmf/tex/context/third/markdown/
    # Run the tests in four parallel threads
    - run: make -j 4 all
    - run: |
        set -e
        cd tests
        circleci tests glob 'testfiles/**/*.test' | parallel -j 4 --halt 2 ./test.sh
