version: 2
jobs:
  build:
    working_directory: ~/Witiko/markdown
    parallelism: 1
    shell: /bin/bash --login
    docker:
    - image: circleci/build-image:ubuntu-14.04-XXL-upstart-1189-5614f37
      command: /sbin/init
    steps:
    - restore_cache:
        keys:
        # This branch if available
        - markdown-{{ .Branch }}-
        # Default branch if not
        - markdown-master-
        # Any branch if there are none on the default branch
        - markdown-
    - run: mkdir -p ~/aptcache/partial
    - run: sudo apt-get -o dir::cache::archives="$HOME"/aptcache update
    - run: sudo apt-get -o dir::cache::archives="$HOME"/aptcache install texlive-full parallel biber
    - save_cache:
        key: markdown-{{ .Branch }}-{{ epoch }}
        paths:
        - ~/aptcache
    - checkout
    - run: xetex markdown.ins
    - run: mkdir -p                ~/texmf/{tex/{luatex,generic,latex,context/third},scripts}/markdown
    - run: cp -f markdown.lua      ~/texmf/tex/luatex/markdown/
    - run: cp -f markdown-cli.lua  ~/texmf/scripts/markdown/
    - run: cp -f markdown.tex      ~/texmf/tex/generic/markdown/
    - run: cp -f markdown.sty      ~/texmf/tex/latex/markdown/
    - run: cp -f t-markdown.tex    ~/texmf/tex/context/third/markdown/
    - run: PARALLEL=-uj1 make all test
