version: 2
jobs:
  build:
    working_directory: ~/Witiko/markdown
    # Distribute the testing to four nodes
    parallelism: 4
    shell: /bin/bash --login
    docker:
    - image: circleci/build-image:ubuntu-14.04-XXL-upstart-1189-5614f37
      command: /sbin/init
    steps:
    - restore_cache:
        keys:
        - markdown-v2.5.5-tl2017-{{ .Branch }}
        - markdown-v2.5.5-tl2017-master
        - markdown-v2.5.5-tl2017-
    # Install TeX Live
    - run: |
        set -e
        if [[ ! -e ~/texlive-cache ]]; then
          wget -O- 'http://mirror.ctan.org/systems/texlive/tlnet/install-tl-unx.tar.gz' | tar xzvC /tmp
          sudo /tmp/install-tl*/install-tl <<<I
          sudo mv /usr/local/texlive ~/texlive-cache
        fi
        echo 'export PATH=/usr/local/texlive/2017/bin/x86_64-linux:"$PATH"' >>$BASH_ENV
    # Install additional packages
    - run: mkdir -p ~/apt-cache/partial
    - run: sudo apt-get -o dir::cache::archives="$HOME"/apt-cache update
    - run: sudo apt-get -o dir::cache::archives="$HOME"/apt-cache install pandoc parallel python-pygments
    - save_cache:
        key: markdown-v2.5.5-tl2017-{{ .Branch }}
        paths:
        - ~/apt-cache/partial
        - ~/texlive-cache
    - checkout
    - run: sudo mv ~/texlive-cache /usr/local/texlive
    - run: xetex markdown.ins
    - run: mkdir -p                ~/texmf/{tex/{luatex,generic,latex,context/third},scripts}/markdown
    - run: cp -f markdown.lua      ~/texmf/tex/luatex/markdown/
    - run: cp -f markdown-cli.lua  ~/texmf/scripts/markdown/
    - run: cp -f markdown.tex      ~/texmf/tex/generic/markdown/
    - run: cp -f markdown.sty      ~/texmf/tex/latex/markdown/
    - run: cp -f t-markdown.tex    ~/texmf/tex/context/third/markdown/
    - run: make all
    - run: |
        set -e
        cd tests
        # Run the tests in two parallel threads
        circleci tests glob 'testfiles/**/*.test' | parallel --jobs 2 --halt 2 ./test.sh
